const productTypes = new Set(["SMARTPHONE", "ACCESSORY"]);
const imagePattern = /^(\/(?!\/)[^\s]{0,499}|https:\/\/[^\s]{1,493})$/i;
const slugPattern = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
export const slugify = (value) => String(value || "").toLowerCase().replace(/\+/g," plus ").normalize("NFKD").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,100);
const own = (body, allowed) => Object.keys(body || {}).every((key) => allowed.includes(key));
const string = (value, max, required=false) => { if (value === undefined || value === null) return required ? null : undefined; if (typeof value !== "string") return null; const v=value.trim(); return (!v && required) || v.length>max ? null : v; };
const number = (value, integer=false) => { if (value === "" || value === null || value === undefined) return null; const n=Number(value); return Number.isFinite(n)&&n>=0&&(!integer||Number.isInteger(n))?n:undefined; };
const bool = (value) => typeof value === "boolean" ? value : undefined;
const jsonObject = (value) => { if (value === undefined || value === null || value === "") return null; try { const parsed=typeof value==="string"?JSON.parse(value):value; return parsed&&typeof parsed==="object"&&!Array.isArray(parsed)?parsed:undefined; } catch{return undefined;} };

export function validateProduct(body, { create=false }={}) {
  const allowed=["name","slug","sku","shortDescription","description","productType","brandId","categoryId","price","originalPrice","stock","lowStockThreshold","imageUrl","imageAltText","specifications","compatibility","isActive","isFeatured","displayOrder"];
  if(!own(body,allowed)) return {error:{_form:"Unsupported product fields were submitted."}};
  const fields={}, data={};
  const required=(key,max)=>{const v=string(body[key],max,create);if(v===null)fields[key]=`${key} is required and must be ${max} characters or fewer.`;else if(v!==undefined)data[key]=v;};
  required("name",160); required("description",5000); required("brandId",100); required("categoryId",100);
  if(body.slug!==undefined||create){const v=slugify(body.slug||body.name);if(!v||!slugPattern.test(v))fields.slug="Enter a valid slug.";else data.slug=v;}
  for(const [key,max] of [["sku",80],["shortDescription",500],["imageAltText",200]]){const v=string(body[key],max);if(v===null)fields[key]=`Invalid ${key}.`;else if(v!==undefined)data[key]=v||null;}
  if(body.productType!==undefined||create){const v=String(body.productType||"").toUpperCase();if(!productTypes.has(v))fields.productType="Select a valid product type.";else data.productType=v;}
  for(const key of ["price","originalPrice"]){if(body[key]!==undefined||key==="price"&&create){const v=number(body[key]);if(v===undefined||key==="price"&&v===null)fields[key]="Enter a non-negative price.";else data[key]=v;}}
  if(data.originalPrice!==null&&data.originalPrice!==undefined&&data.price!==undefined&&data.originalPrice<data.price)fields.originalPrice="Original price must be at least the selling price.";
  for(const key of ["lowStockThreshold","displayOrder",...(create?["stock"]:[])]){if(body[key]!==undefined||create&&key!=="displayOrder"){const v=number(body[key],true);if(v===undefined||v===null)fields[key]="Enter a non-negative whole number.";else data[key]=v;}}
  if(!create&&body.stock!==undefined)fields.stock="Use inventory adjustment to change stock.";
  if(body.imageUrl!==undefined||create){const v=string(body.imageUrl,500,create);if(v===null||!imagePattern.test(v))fields.imageUrl="Use a local /path or an HTTPS image URL.";else data.imageUrl=v;}
  for(const key of ["specifications","compatibility"]){if(body[key]!==undefined){const v=jsonObject(body[key]);if(v===undefined)fields[key]=`${key} must be a JSON object.`;else data[key]=v;}}
  for(const key of ["isActive","isFeatured"]){if(body[key]!==undefined){const v=bool(body[key]);if(v===undefined)fields[key]=`${key} must be true or false.`;else data[key]=v;}}
  return Object.keys(fields).length?{error:fields}:{data};
}

export function validateBrand(body){const allowed=["name","slug","logoUrl","description","isActive","displayOrder"];if(!own(body,allowed))return{error:{_form:"Unsupported brand fields."}};const fields={},data={};const name=string(body.name,100,true);if(!name)fields.name="Brand name is required.";else data.name=name;const slug=slugify(body.slug||name);if(!slug)fields.slug="Valid slug required.";else data.slug=slug;for(const[key,max]of[["logoUrl",500],["description",1000]]){if(body[key]!==undefined){const v=string(body[key],max);if(v===null||(key==="logoUrl"&&v&&!imagePattern.test(v)))fields[key]="Invalid value.";else data[key]=v||null;}}if(body.isActive!==undefined){const v=bool(body.isActive);if(v===undefined)fields.isActive="Invalid status.";else data.isActive=v;}if(body.displayOrder!==undefined){const v=number(body.displayOrder,true);if(v===undefined||v===null)fields.displayOrder="Enter a non-negative whole number.";else data.displayOrder=v;}return Object.keys(fields).length?{error:fields}:{data};}
export function validateCategory(body){const allowed=["name","slug","description","imageUrl","productType","isActive","displayOrder"];if(!own(body,allowed))return{error:{_form:"Unsupported category fields."}};const base=validateBrand({name:body.name,slug:body.slug,description:body.description,logoUrl:body.imageUrl,isActive:body.isActive,displayOrder:body.displayOrder});if(base.error)return base;const type=String(body.productType||"").toUpperCase();if(!productTypes.has(type))return{error:{productType:"Select a valid product type."}};base.data.imageUrl=base.data.logoUrl;delete base.data.logoUrl;base.data.productType=type;return base;}
export function validateAdjustment(body){const fields={};if(!own(body,["productId","adjustmentType","quantity","reason","note"]))fields._form="Unsupported inventory fields.";const productId=string(body.productId,100,true);if(!productId)fields.productId="Product is required.";const adjustmentType=String(body.adjustmentType||"").toUpperCase();if(!["ADD","REMOVE","SET"].includes(adjustmentType))fields.adjustmentType="Select ADD, REMOVE, or SET.";const quantity=number(body.quantity,true);if(quantity===undefined||quantity===null||(adjustmentType!=="SET"&&quantity<1))fields.quantity="Enter a valid whole quantity.";const reason=String(body.reason||"").toUpperCase();if(!["ADMIN_ADJUSTMENT","RESTOCK","CORRECTION","RETURN"].includes(reason))fields.reason="Select a valid reason.";const note=string(body.note,500);if(note===null)fields.note="Note is limited to 500 characters.";return Object.keys(fields).length?{error:fields}:{data:{productId,adjustmentType,quantity,reason,note:note||null}};}
