import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useMemo, useState } from "react";
import { FiBatteryCharging, FiChevronLeft, FiChevronRight, FiClock, FiHeadphones, FiHeart, FiMusic, FiSearch, FiShield, FiShoppingCart, FiSmartphone, FiZap } from "react-icons/fi";
import Footer from "@/components/layout/Footer";
import { useCart } from "@/context/CartContext";
import { useWishlist } from "@/context/WishlistContext";
import { useCategories, useProducts } from "@/hooks/useCatalogue";
import styles from "@/styles/accessories.module.css";

const categoryIcons = { "Smart Watches": FiClock, Earphones: FiHeadphones, "Power Banks": FiBatteryCharging, Chargers: FiZap, Cables: FiZap, "Mobile Covers": FiSmartphone, "Tempered Glass": FiShield, "Other Accessories": FiMusic };
const sortMap = { featured: "featured", "price-low": "price-asc", "price-high": "price-desc", newest: "newest", rating: "featured" };
function AccessoryVisual({ category, variant }) { const Icon = categoryIcons[category] || FiSmartphone; return <div className={`${styles.accessoryVisual} ${styles[`variant${variant}`]}`}><span /><Icon aria-hidden="true" /></div>; }

export default function AccessoriesPage() {
  const router = useRouter();
  const { addToCart: addCartItem } = useCart(); const { isInWishlist, toggleWishlist } = useWishlist();
  const [activeCategory, setActiveCategory] = useState("all"), [query, setQuery] = useState(""), [sort, setSort] = useState("featured"), [page, setPage] = useState(1), [added, setAdded] = useState([]);
  useEffect(() => { if (router.isReady && typeof router.query.category === "string" && /^[a-z0-9-]+$/.test(router.query.category)) setActiveCategory(router.query.category); }, [router.isReady, router.query.category]);
  const filters = useMemo(() => ({ type: "ACCESSORY", category: activeCategory, search: query.trim(), sort: sortMap[sort], page, limit: 16 }), [activeCategory, page, query, sort]);
  const { products, pagination, loading, error, retry } = useProducts(filters); const { categories } = useCategories("ACCESSORY");
  const currentPage = pagination.page || page, totalPages = pagination.totalPages || 0;
  const chooseCategory = (slug) => { setActiveCategory((current) => current === slug ? "all" : slug); setPage(1); };
  const addToCart = (product) => { if (!product.inStock) return; addCartItem(product, "accessory"); setAdded((items) => [...new Set([...items, product.id])]); window.setTimeout(() => setAdded((items) => items.filter((id) => id !== product.id)), 1500); };
  return <><Head><title>Accessories | The Cellphone Studio</title><meta name="description" content="Explore premium mobile accessories from trusted brands at The Cellphone Studio." /></Head><main className={styles.page}>
    <section className={styles.hero} aria-labelledby="accessories-title"><div className={`${styles.container} ${styles.heroInner}`}><div className={styles.heroCopy}><p>Accessories</p><h1 id="accessories-title">Complete Your Mobile Experience</h1><span>Explore premium accessories from trusted brands.</span></div><div className={styles.heroArt} aria-hidden="true"><div className={styles.heroWatch}><FiClock /></div><div className={styles.heroBuds}><FiHeadphones /></div><div className={styles.heroCharger}><FiZap /></div></div></div></section>
    <section className={`${styles.container} ${styles.categories}`} aria-labelledby="categories-title"><div className={styles.sectionHeading}><div><p>Find your essential</p><h2 id="categories-title">Shop by Category</h2></div></div><div className={styles.categoryGrid}>{categories.map((category) => { const Icon = categoryIcons[category.name] || FiSmartphone, active = activeCategory === category.slug; return <button className={`${styles.categoryCard} ${active ? styles.categoryActive : ""}`} type="button" onClick={() => chooseCategory(category.slug)} aria-pressed={active} key={category.id}><span><Icon /></span><strong>{category.name}</strong><small>{category.productCount} products</small></button>; })}</div></section>
    <section className={`${styles.container} ${styles.catalog}`} aria-labelledby="products-title"><div className={styles.toolbar}><div><label className={styles.search}><span className={styles.srOnly}>Search accessories</span><FiSearch /><input type="search" placeholder="Search accessories..." value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} /></label><p aria-live="polite">{loading ? "Loading accessories..." : `${pagination.total || 0} accessories found`}</p></div><label className={styles.sort}>Sort by <select value={sort} onChange={(event) => { setSort(event.target.value); setPage(1); }}><option value="featured">Featured</option><option value="price-low">Price Low to High</option><option value="price-high">Price High to Low</option><option value="newest">Newest</option><option value="rating">Best Rating</option></select></label></div><h2 className={styles.srOnly} id="products-title">Accessory products</h2>
      {error ? <Message title="We could not load accessories" text={error} action="Try Again" onClick={retry} /> : loading ? <Message title="Loading accessories..." text="Please wait while we retrieve the latest catalogue." /> : products.length ? <div className={styles.productGrid}>{products.map((product) => { const wished = isInWishlist(product.id, "accessory"), isAdded = added.includes(product.id); return <article className={styles.productCard} key={product.id}><Link className={styles.productLink} href={product.route} aria-label={`View ${product.name} details`}><div className={`${styles.productImage} ${styles[`image${product.visual}`]}`}><span className={styles.badge}>{product.inStock ? product.badge || `${product.discount}% OFF` : "OUT OF STOCK"}</span><AccessoryVisual category={product.category} variant={product.visual} /></div><div className={styles.productInfo}><p>{product.brand}</p><h3>{product.name}</h3><small className={styles.categoryName}>{product.category}</small><div className={styles.rating}><span>★</span><strong>{product.rating || "—"}</strong><small>({product.reviewCount})</small></div><div className={styles.prices}><strong>₹{product.price.toLocaleString("en-IN")}</strong>{product.oldPrice && <del>₹{product.oldPrice.toLocaleString("en-IN")}</del>}<span>{product.discount}% off</span></div><p className={styles.emi}>EMI available from ₹{Math.ceil(product.price / 6).toLocaleString("en-IN")}/month</p></div></Link><button className={`${styles.wishlist} ${wished ? styles.wished : ""}`} type="button" onClick={(event) => { event.preventDefault(); event.stopPropagation(); toggleWishlist(product, "accessory"); }} aria-label={`${wished ? "Remove" : "Add"} ${product.name} ${wished ? "from" : "to"} wishlist`} aria-pressed={wished}><FiHeart /></button><button className={`${styles.cartButton} ${isAdded ? styles.added : ""}`} type="button" onClick={(event) => { event.preventDefault(); event.stopPropagation(); addToCart(product); }} disabled={isAdded || !product.inStock}><FiShoppingCart /> {!product.inStock ? "Out of Stock" : isAdded ? "Added" : "Add to Cart"}</button></article>; })}</div> : <Message title="No accessories found" text="Try another search or category." action="View all accessories" onClick={() => { setQuery(""); setActiveCategory("all"); }} />}
      {!loading && !error && products.length > 0 && <nav className={styles.pagination} aria-label="Accessory pages"><button type="button" onClick={() => setPage((value) => Math.max(1, value - 1))} disabled={currentPage === 1}><FiChevronLeft /> Previous</button>{Array.from({ length: totalPages }, (_, index) => index + 1).map((number) => <button className={currentPage === number ? styles.currentPage : ""} type="button" onClick={() => setPage(number)} aria-current={currentPage === number ? "page" : undefined} key={number}>{number}</button>)}<button type="button" onClick={() => setPage((value) => Math.min(totalPages, value + 1))} disabled={currentPage === totalPages}>Next <FiChevronRight /></button></nav>}
    </section>
  </main><Footer /></>;
}
function Message({ title, text, action, onClick }) { return <div className={styles.empty} role="status"><h3>{title}</h3><p>{text}</p>{action && <button type="button" onClick={onClick}>{action}</button>}</div>; }
