import { Prisma } from "@/lib/generated/prisma/client";
import { prisma } from "@/lib/prisma";
import { validateAdjustment, validateBrand, validateCategory, validateProduct } from "@/server/validation/adminValidation";

const pageOf=(q)=>({page:Math.max(1,Math.min(100000,parseInt(q.page,10)||1)),limit:Math.max(1,Math.min(50,parseInt(q.limit,10)||20))});
const activeValue=(v)=>v==="true"?true:v==="false"?false:undefined;
const typeValue=(v)=>["SMARTPHONE","ACCESSORY"].includes(String(v||"").toUpperCase())?String(v).toUpperCase():undefined;
const productAdminSelect={id:true,slug:true,sku:true,name:true,productType:true,price:true,originalPrice:true,stock:true,reservedStock:true,lowStockThreshold:true,imageUrl:true,isActive:true,isFeatured:true,displayOrder:true,updatedAt:true,brand:{select:{id:true,name:true}},category:{select:{id:true,name:true}},images:{select:{id:true,imageUrl:true,altText:true,isPrimary:true},orderBy:{displayOrder:"asc"}}};
const productDetailSelect={...productAdminSelect,shortDescription:true,description:true,specifications:true,compatibility:true,legacyId:true};
const audit=(tx,adminUserId,action,entityType,entityId,metadata)=>tx.adminAuditLog.create({data:{adminUserId,action,entityType,entityId,metadata}});

function stockWhere(status){if(status==="out-of-stock")return{stock:0};if(status==="in-stock")return{stock:{gt:0},NOT:{stock:{lte:prisma.product.fields.lowStockThreshold}}};if(status==="low-stock")return{stock:{gt:0,lte:prisma.product.fields.lowStockThreshold}};return{};}
export async function listAdminProducts(query){const{page,limit}=pageOf(query);const search=String(query.search||"").trim().slice(0,80);const where={...(search?{OR:[{name:{contains:search,mode:"insensitive"}},{sku:{contains:search,mode:"insensitive"}},{slug:{contains:search,mode:"insensitive"}}]}:{}),...(typeValue(query.type)?{productType:typeValue(query.type)}:{}),...(query.brand?{brandId:String(query.brand)}:{}),...(query.category?{categoryId:String(query.category)}:{}),...(activeValue(query.active)!==undefined?{isActive:activeValue(query.active)}:{}),...(activeValue(query.featured)!==undefined?{isFeatured:activeValue(query.featured)}:{}),...stockWhere(query.stockStatus)};const sort={"price-asc":{price:"asc"},"price-desc":{price:"desc"},"stock-asc":{stock:"asc"},"stock-desc":{stock:"desc"},"name-asc":{name:"asc"},oldest:{updatedAt:"asc"}}[query.sort]||{updatedAt:"desc"};const[products,total]=await prisma.$transaction([prisma.product.findMany({where,select:productAdminSelect,orderBy:sort,skip:(page-1)*limit,take:limit}),prisma.product.count({where})]);return{products:products.map(serializeAdminProduct),pagination:{page,limit,total,totalPages:Math.ceil(total/limit)}};}
export const serializeAdminProduct=(p)=>({...p,price:Number(p.price),originalPrice:p.originalPrice===null?null:Number(p.originalPrice),availableStock:Math.max(0,p.stock-(p.reservedStock||0)),updatedAt:p.updatedAt?.toISOString?.()||p.updatedAt,stockStatus:p.stock-(p.reservedStock||0)<=0?"OUT_OF_STOCK":p.stock-(p.reservedStock||0)<=p.lowStockThreshold?"LOW_STOCK":"IN_STOCK"});
export async function getAdminProduct(id){const p=await prisma.product.findUnique({where:{id},select:productDetailSelect});return p?serializeAdminProduct(p):null;}
async function validateRelations(data,current){const type=data.productType||current?.productType;const brandId=data.brandId||current?.brandId;const categoryId=data.categoryId||current?.categoryId;const[brand,category]=await Promise.all([prisma.brand.findUnique({where:{id:brandId},select:{id:true,isActive:true}}),prisma.category.findUnique({where:{id:categoryId},select:{id:true,isActive:true,productType:true}})]);const fields={};if(!brand)fields.brandId="Brand was not found.";else if(!brand.isActive)fields.brandId="Select an active brand.";if(!category)fields.categoryId="Category was not found.";else if(!category.isActive)fields.categoryId="Select an active category.";else if(category.productType!==type)fields.categoryId="Category type must match the product type.";return Object.keys(fields).length?fields:null;}
export async function createProduct(body,admin){const checked=validateProduct(body,{create:true});if(checked.error)return{fields:checked.error};const relationErrors=await validateRelations(checked.data);if(relationErrors)return{fields:relationErrors};const{imageAltText,stock=0,...data}=checked.data;const product=await prisma.$transaction(async(tx)=>{const created=await tx.product.create({data:{...data,stock},select:productDetailSelect});if(data.imageUrl)await tx.productImage.create({data:{productId:created.id,imageUrl:data.imageUrl,altText:imageAltText||created.name,isPrimary:true}});if(stock>0)await tx.inventoryMovement.create({data:{productId:created.id,quantityChange:stock,previousStock:0,newStock:stock,reason:"INITIAL_STOCK",note:"Initial stock entered during product creation.",adminUserId:admin.id}});await audit(tx,admin.id,"PRODUCT_CREATED","PRODUCT",created.id,{slug:created.slug,sku:created.sku});return created;});return{product:serializeAdminProduct(product)};}
export async function updateProduct(id,body,admin){const current=await prisma.product.findUnique({where:{id},select:{id:true,productType:true,brandId:true,categoryId:true,isActive:true}});if(!current)return null;const checked=validateProduct(body);if(checked.error)return{fields:checked.error};const relationErrors=await validateRelations(checked.data,current);if(relationErrors)return{fields:relationErrors};const{imageAltText,...data}=checked.data;const product=await prisma.$transaction(async(tx)=>{const updated=await tx.product.update({where:{id},data,select:productDetailSelect});if(data.imageUrl){await tx.productImage.deleteMany({where:{productId:id,isPrimary:true}});await tx.productImage.create({data:{productId:id,imageUrl:data.imageUrl,altText:imageAltText||updated.name,isPrimary:true}});}const action=data.isActive===false&&current.isActive?"PRODUCT_DEACTIVATED":data.isActive===true&&!current.isActive?"PRODUCT_REACTIVATED":"PRODUCT_UPDATED";await audit(tx,admin.id,action,"PRODUCT",id,{fields:Object.keys(data)});return updated;});return{product:serializeAdminProduct(product)};}
export async function deactivateProduct(id,admin){const current=await prisma.product.findUnique({where:{id},select:{id:true,isActive:true}});if(!current)return null;await prisma.$transaction(async(tx)=>{await tx.product.update({where:{id},data:{isActive:false}});await audit(tx,admin.id,"PRODUCT_DEACTIVATED","PRODUCT",id,null);});return{isActive:false};}

export async function listAdminBrands(query={}){const search=String(query.search||"").trim().slice(0,80);const rows=await prisma.brand.findMany({where:search?{name:{contains:search,mode:"insensitive"}}:{},select:{id:true,name:true,slug:true,logoUrl:true,description:true,isActive:true,displayOrder:true,_count:{select:{products:true}}},orderBy:[{displayOrder:"asc"},{name:"asc"}]});const activeCounts=await prisma.product.groupBy({by:["brandId"],where:{isActive:true},_count:{_all:true}});const map=new Map(activeCounts.map(x=>[x.brandId,x._count._all]));return rows.map(x=>({...x,productCount:x._count.products,activeProductCount:map.get(x.id)||0,_count:undefined}));}
export async function saveBrand(id,body,admin){const checked=validateBrand(body);if(checked.error)return{fields:checked.error};return prisma.$transaction(async(tx)=>{const brand=id?await tx.brand.update({where:{id},data:checked.data}):await tx.brand.create({data:checked.data});await audit(tx,admin.id,id?"BRAND_UPDATED":"BRAND_CREATED","BRAND",brand.id,{slug:brand.slug});return{brand};});}
export async function setBrandActive(id,isActive,admin){const brand=await prisma.brand.findUnique({where:{id},select:{id:true,_count:{select:{products:{where:{isActive:true}}}}}});if(!brand)return null;await prisma.$transaction(async(tx)=>{await tx.brand.update({where:{id},data:{isActive}});await audit(tx,admin.id,isActive?"BRAND_REACTIVATED":"BRAND_DEACTIVATED","BRAND",id,{activeProducts:brand._count.products});});return{isActive,activeProductCount:brand._count.products};}
export async function listAdminCategories(query={}){const search=String(query.search||"").trim().slice(0,80);return prisma.category.findMany({where:{...(search?{name:{contains:search,mode:"insensitive"}}:{}),...(typeValue(query.type)?{productType:typeValue(query.type)}:{})},select:{id:true,name:true,slug:true,description:true,imageUrl:true,productType:true,isActive:true,displayOrder:true,_count:{select:{products:true}}},orderBy:[{displayOrder:"asc"},{name:"asc"}]}).then(rows=>rows.map(x=>({...x,productCount:x._count.products,_count:undefined})));}
export async function saveCategory(id,body,admin){const checked=validateCategory(body);if(checked.error)return{fields:checked.error};if(id){const existing=await prisma.category.findUnique({where:{id},select:{productType:true,_count:{select:{products:true}}}});if(!existing)return null;if(existing._count.products&&existing.productType!==checked.data.productType)return{fields:{productType:"Product type cannot change while products use this category."}};}return prisma.$transaction(async(tx)=>{const category=id?await tx.category.update({where:{id},data:checked.data}):await tx.category.create({data:checked.data});await audit(tx,admin.id,id?"CATEGORY_UPDATED":"CATEGORY_CREATED","CATEGORY",category.id,{slug:category.slug});return{category};});}
export async function setCategoryActive(id,isActive,admin){const category=await prisma.category.findUnique({where:{id},select:{id:true,_count:{select:{products:{where:{isActive:true}}}}}});if(!category)return null;await prisma.$transaction(async(tx)=>{await tx.category.update({where:{id},data:{isActive}});await audit(tx,admin.id,isActive?"CATEGORY_REACTIVATED":"CATEGORY_DEACTIVATED","CATEGORY",id,{activeProducts:category._count.products});});return{isActive,activeProductCount:category._count.products};}

export async function dashboardData(){const[active,inactive,brands,categories,stock,featured,recent,low]=await Promise.all([prisma.product.count({where:{isActive:true}}),prisma.product.count({where:{isActive:false}}),prisma.brand.count(),prisma.category.count(),prisma.product.aggregate({_sum:{stock:true}}),prisma.product.count({where:{isFeatured:true,isActive:true}}),prisma.product.findMany({select:productAdminSelect,orderBy:{updatedAt:"desc"},take:6}),prisma.product.findMany({where:{isActive:true,OR:[{stock:0},{stock:{gt:0,lte:prisma.product.fields.lowStockThreshold}}]},select:productAdminSelect,orderBy:{stock:"asc"},take:6})]);return{stats:{activeProducts:active,inactiveProducts:inactive,totalBrands:brands,totalCategories:categories,totalStock:stock._sum.stock||0,outOfStock:await prisma.product.count({where:{stock:0,isActive:true}}),lowStock:await prisma.product.count({where:{stock:{gt:0,lte:prisma.product.fields.lowStockThreshold},isActive:true}}),featuredProducts:featured},recent:recent.map(serializeAdminProduct),lowStockProducts:low.map(serializeAdminProduct)};}
export async function listInventory(query){return listAdminProducts({...query,sort:query.sort||"stock-asc"});}
export async function adjustInventory(body,admin){const checked=validateAdjustment(body);if(checked.error)return{fields:checked.error};const input=checked.data;for(let attempt=0;attempt<3;attempt++){try{return await prisma.$transaction(async(tx)=>{const product=await tx.product.findUnique({where:{id:input.productId},select:{id:true,stock:true,name:true}});if(!product)return null;const next=input.adjustmentType==="ADD"?product.stock+input.quantity:input.adjustmentType==="REMOVE"?product.stock-input.quantity:input.quantity;if(next<0)return{fields:{quantity:"Adjustment would make stock negative."}};const updated=await tx.product.updateMany({where:{id:product.id,stock:product.stock},data:{stock:next}});if(updated.count!==1)throw new Prisma.PrismaClientKnownRequestError("Concurrent stock update",{code:"P2034",clientVersion:"7"});const movement=await tx.inventoryMovement.create({data:{productId:product.id,quantityChange:next-product.stock,previousStock:product.stock,newStock:next,reason:input.reason,note:input.note,adminUserId:admin.id,referenceType:"ADMIN_ADJUSTMENT"},select:{id:true,previousStock:true,newStock:true,quantityChange:true,reason:true,createdAt:true}});await audit(tx,admin.id,"INVENTORY_ADJUSTED","PRODUCT",product.id,{previousStock:product.stock,newStock:next,reason:input.reason});return{productId:product.id,productName:product.name,stock:next,movement};},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}catch(error){if(error.code==="P2034"&&attempt<2)continue;throw error;}}}
export async function inventoryHistory(productId,query={}){const{page,limit}=pageOf(query);const product=await prisma.product.findUnique({where:{id:productId},select:{id:true,name:true,sku:true,stock:true}});if(!product)return null;const where={productId};const[movements,total]=await prisma.$transaction([prisma.inventoryMovement.findMany({where,select:{id:true,quantityChange:true,previousStock:true,newStock:true,reason:true,referenceType:true,referenceId:true,note:true,createdAt:true,adminUser:{select:{name:true,email:true}}},orderBy:{createdAt:"desc"},skip:(page-1)*limit,take:limit}),prisma.inventoryMovement.count({where})]);return{product,movements,pagination:{page,limit,total,totalPages:Math.ceil(total/limit)}};}
