import Link from "next/link";
import { FiBatteryCharging, FiHeadphones, FiHeart, FiShield, FiSmartphone, FiSpeaker, FiWatch, FiZap } from "react-icons/fi";
import { useCart } from "@/context/CartContext";
import { useWishlist } from "@/context/WishlistContext";
import { useProducts } from "@/hooks/useCatalogue";
const filters={type:"ACCESSORY",featured:true,limit:8,sort:"featured"};
const icons={"Smart Watches":FiWatch,Earphones:FiHeadphones,"Power Banks":FiBatteryCharging,Chargers:FiZap,Cables:FiZap,"Mobile Covers":FiSmartphone,"Tempered Glass":FiShield,"Other Accessories":FiSpeaker};
const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0});
export default function FeaturedAccessories(){const{products,loading,error,retry}=useProducts(filters);const{addToCart}=useCart();const{isInWishlist,toggleWishlist}=useWishlist();return <section className="featured-accessories" aria-labelledby="featured-accessories-title"><div className="featured-products-container"><p className="section-label">Featured Accessories</p><span className="section-accent" aria-hidden="true"/><h2 id="featured-accessories-title">Complete Your Mobile Experience</h2><p className="featured-products-subheading">Explore popular mobile accessories, audio products, wearables and charging essentials.</p>{loading?<State text="Loading featured accessories..."/>:error?<State text="Featured accessories are temporarily unavailable." action="Try Again" onClick={retry}/>:products.length?<div className="products-grid accessories-grid">{products.map((product)=>{const Icon=icons[product.category]||FiSmartphone;const wished=isInWishlist(product.id,"accessory");return <article className="product-card accessory-card" key={product.id}><div className="accessory-card-top"><span className={`product-badge ${product.inStock?"product-badge-popular":"product-badge-limited"}`}>{product.inStock?"FEATURED":"OUT OF STOCK"}</span></div><Link href={product.route} className="product-image-wrap accessory-image-wrap" aria-label={`View ${product.name} details`}><span className="product-placeholder-glow" aria-hidden="true"/><Icon aria-hidden="true"/></Link><div className="product-details"><p className="product-brand-name">{product.category}</p><h3>{product.name}</h3><div className="product-rating" aria-label={`${product.rating||0} out of 5 stars`}><span aria-hidden="true">{"★".repeat(Math.round(product.rating||0))}{"☆".repeat(5-Math.round(product.rating||0))}</span></div><div className="product-pricing"><strong>{money.format(product.price)}</strong>{product.oldPrice&&<del>{money.format(product.oldPrice)}</del>}</div><p className="product-emi">EMI Available</p></div><div className="product-actions"><button className="add-to-cart" type="button" disabled={!product.inStock} onClick={()=>product.inStock&&addToCart(product,"accessory")}>{product.inStock?"Add to Cart":"Out of Stock"}</button><button className="wishlist-button" type="button" aria-pressed={wished} aria-label={`${wished?"Remove":"Add"} ${product.name} ${wished?"from":"to"} wishlist`} onClick={()=>toggleWishlist(product,"accessory")}><FiHeart/></button></div></article>})}</div>:<State text="No featured accessories are available yet."/>}<Link className="view-all-products" href="/accessories">View All Accessories →</Link></div></section>}
function State({text,action,onClick}){return <div className="catalogue-home-state" role="status"><p>{text}</p>{action&&<button type="button" onClick={onClick}>{action}</button>}</div>}
