import Image from "next/image";
import Link from "next/link";
import { FiHeart, FiSmartphone } from "react-icons/fi";
import { useCart } from "@/context/CartContext";
import { useWishlist } from "@/context/WishlistContext";
import { useProducts } from "@/hooks/useCatalogue";

const filters = { type: "SMARTPHONE", featured: true, limit: 8, sort: "featured" };
const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });
export default function FeaturedProducts() {
  const { products, loading, error, retry } = useProducts(filters); const { addToCart } = useCart(); const { isInWishlist, toggleWishlist } = useWishlist();
  return <section className="featured-products" aria-labelledby="featured-products-title"><div className="featured-products-container"><p className="section-label">Featured Smartphones</p><span className="section-accent" aria-hidden="true" /><h2 id="featured-products-title">Latest Smartphones</h2><p className="featured-products-subheading">Discover the newest flagship and best-selling smartphones from the world&apos;s leading brands.</p>
    {loading ? <CatalogueState text="Loading featured smartphones..." /> : error ? <CatalogueState text="Featured smartphones are temporarily unavailable." action="Try Again" onClick={retry} /> : products.length ? <div className="products-grid">{products.map((product) => { const wished = isInWishlist(product.id, "smartphone"); return <article className="product-card" key={product.id}><div className="product-card-top">{product.brandLogo ? <Image className="product-brand-logo" src={product.brandLogo} alt={`${product.brand} logo`} width={120} height={60} sizes="78px" /> : <strong>{product.brand}</strong>}<span className={`product-badge ${product.inStock ? "product-badge-best" : "product-badge-limited"}`}>{product.inStock ? "FEATURED" : "OUT OF STOCK"}</span></div><Link href={product.route} className="product-image-wrap" aria-label={`View ${product.name} details`}><span className="product-placeholder-glow" aria-hidden="true" /><FiSmartphone aria-hidden="true" /></Link><div className="product-details"><p className="product-brand-name">{product.brand}</p><h3>{product.name}</h3><div className="product-rating" aria-label={`${product.rating || 0} out of 5 stars`}><span aria-hidden="true">{"★".repeat(Math.round(product.rating || 0))}{"☆".repeat(5-Math.round(product.rating || 0))}</span></div><div className="product-pricing"><strong>{money.format(product.price)}</strong>{product.oldPrice && <del>{money.format(product.oldPrice)}</del>}</div><p className="product-emi">EMI Available</p></div><div className="product-actions"><button className="add-to-cart" type="button" disabled={!product.inStock} onClick={() => product.inStock && addToCart(product,"smartphone")}>{product.inStock ? "Add to Cart" : "Out of Stock"}</button><button className="wishlist-button" type="button" aria-pressed={wished} aria-label={`${wished ? "Remove" : "Add"} ${product.name} ${wished ? "from" : "to"} wishlist`} onClick={() => toggleWishlist(product,"smartphone")}><FiHeart aria-hidden="true" /></button></div></article>; })}</div> : <CatalogueState text="No featured smartphones are available yet." />}
    <Link className="view-all-products" href="/smartphones">View All Smartphones</Link></div></section>;
}
function CatalogueState({text,action,onClick}){return <div className="catalogue-home-state" role="status"><p>{text}</p>{action&&<button type="button" onClick={onClick}>{action}</button>}</div>}
