import{createContext,useCallback,useContext,useEffect,useRef,useState}from"react";import toast from"react-hot-toast";import{useAuth}from"./AuthContext";
const WishlistContext=createContext(null),KEY="tcs_guest_wishlist_v2",LEGACY="cellphoneStudioWishlist",LIMIT=200;
export function normalizeWishlistProduct(product,type){if(!product)return null;const raw=product.productId??product.id,productId=raw===undefined||raw===null?"":String(raw).trim(),slug=typeof product.slug==="string"?product.slug:null,legacyId=product.legacyId??(/^\d+$/.test(productId)?productId:null);if(!productId&&!slug&&legacyId===null)return null;const productType=(type||product.productType||"").toLowerCase().includes("access")?"accessory":"smartphone",id=productId||slug||String(legacyId);return{wishlistKey:`${productType}-${id}`,productId,id,slug,legacyId,productType,addedAt:Number.isFinite(Date.parse(product.addedAt))?product.addedAt:new Date().toISOString(),name:product.name||"Saved product",brand:product.brand||"The Cellphone Studio",price:Number.isFinite(Number(product.price))?Number(product.price):0,originalPrice:Number(product.originalPrice||product.oldPrice)||null,image:product.image||product.imageUrl||null,imageUrl:product.imageUrl||product.image||null,stock:Number(product.availableStock??product.stock)||0,inStock:product.inStock??Number(product.stock)>0,isActive:product.isActive!==false,rating:Number(product.rating)||null,detailRoute:product.detailRoute||product.route||(productType==="smartphone"?`/product/${id}`:`/accessory/${id}`),route:product.route||product.detailRoute}}
function readGuest(){try{const v2=JSON.parse(localStorage.getItem(KEY)||"null"),legacy=JSON.parse(localStorage.getItem(LEGACY)||"[]"),source=Array.isArray(v2?.items)?v2.items:Array.isArray(v2)?v2:Array.isArray(legacy)?legacy:[],seen=new Set(),items=[];for(const raw of source){const item=normalizeWishlistProduct(raw,raw?.productType);if(item&&!seen.has(item.wishlistKey)){seen.add(item.wishlistKey);items.push(item)}if(items.length===LIMIT)break}localStorage.setItem(KEY,JSON.stringify({version:2,items}));if(!Array.isArray(v2?.items))localStorage.removeItem(LEGACY);return items}catch{return[]}}
function writeGuest(items){try{localStorage.setItem(KEY,JSON.stringify({version:2,items:items.slice(0,LIMIT)}));return true}catch{return false}}
export function WishlistProvider({children}){const{user,loading:authLoading}=useAuth(),[wishlistItems,setItems]=useState([]),[wishlistReady,setReady]=useState(false),[error,setError]=useState(""),[pending,setPending]=useState(new Set()),lastUser=useRef(undefined);
 const refreshWishlist=useCallback(async()=>{if(!user)return;const r=await fetch("/api/wishlist?limit=50"),j=await r.json();if(!r.ok)throw new Error(j.error?.message||"Unable to load wishlist.");setItems(j.data.items);return j.data},[user]);
 const mergeGuestWishlist=useCallback(async()=>{const guest=readGuest();if(!user||!guest.length)return true;const r=await fetch("/api/wishlist/merge",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:guest.map(x=>({productId:x.productId||undefined,slug:x.slug||undefined,legacyId:x.legacyId??undefined}))})});if(!r.ok)return false;try{localStorage.removeItem(KEY);localStorage.removeItem(LEGACY)}catch{}return true},[user]);
 useEffect(()=>{if(authLoading)return;let active=true;(async()=>{setReady(false);setError("");if(user){const merged=await mergeGuestWishlist();try{await refreshWishlist();if(!merged)toast("Your account is ready, but some browser wishlist items could not be synced.")}catch(e){if(active){setItems([]);setError(e.message)}}}else setItems(readGuest());if(active){setReady(true);lastUser.current=user?.id||null}})();return()=>{active=false}},[authLoading,user?.id,mergeGuestWishlist,refreshWishlist]);
 const mutate=async(product,type,desired)=>{const item=normalizeWishlistProduct(product,type);if(!item||pending.has(item.productId))return false;const before=wishlistItems,wished=before.some(x=>x.productId===item.productId||x.wishlistKey===item.wishlistKey),next=desired??!wished;setPending(s=>new Set(s).add(item.productId));setItems(next?[item,...before.filter(x=>x.productId!==item.productId)]:before.filter(x=>x.productId!==item.productId&&x.wishlistKey!==item.wishlistKey));try{if(user){const r=await fetch(next?"/api/wishlist":`/api/wishlist/${encodeURIComponent(item.productId)}`,{method:next?"POST":"DELETE",headers:next?{"Content-Type":"application/json"}:undefined,body:next?JSON.stringify({productId:item.productId}):undefined}),j=await r.json();if(!r.ok)throw new Error(j.error?.message||"Wishlist could not be updated.");await refreshWishlist()}else if(!writeGuest(next?[item,...before.filter(x=>x.wishlistKey!==item.wishlistKey)]:before.filter(x=>x.wishlistKey!==item.wishlistKey)))throw new Error("Browser storage is unavailable.");toast.success(next?"Added to your wishlist.":"Removed from your wishlist.");return next}catch(e){setItems(before);setError(e.message);toast.error(e.message);return wished}finally{setPending(s=>{const n=new Set(s);n.delete(item.productId);return n})}};
 const removeFromWishlist=(value,silent=false)=>{const item=wishlistItems.find(x=>x.wishlistKey===value||x.productId===value||x.id===value);if(!item)return false;const result=mutate(item,item.productType,false);if(silent)return result;return result};
 const clearWishlist=async()=>{const before=wishlistItems;setItems([]);try{if(user){const r=await fetch("/api/wishlist",{method:"DELETE"});if(!r.ok)throw new Error("Unable to clear wishlist.")}else writeGuest([]);toast.success("Wishlist cleared.")}catch(e){setItems(before);toast.error(e.message)}};
 const isInWishlist=(id)=>wishlistItems.some(x=>String(x.productId||x.id)===String(id));
 return <WishlistContext.Provider value={{wishlistItems,items:wishlistItems,wishlistCount:wishlistItems.length,count:wishlistItems.length,wishlistReady,isInitialized:wishlistReady,isLoading:!wishlistReady,error,pendingProductIds:pending,addToWishlist:(p,t)=>mutate(p,t,true),removeFromWishlist,toggleWishlist:(p,t)=>mutate(p,t),clearWishlist,refreshWishlist,mergeGuestWishlist,getGuestWishlist:readGuest,normalizeWishlistProduct,isInWishlist,isWishlisted:isInWishlist}}>{children}</WishlistContext.Provider>}
export function useWishlist(){const value=useContext(WishlistContext);if(!value)throw new Error("useWishlist must be used inside WishlistProvider");return value}
