import{prisma}from"@/lib/prisma";export class WishlistError extends Error{constructor(status,code,message){super(message);Object.assign(this,{status,code})}}export const LIMIT=200;
const productInclude={brand:{select:{name:true}},category:{select:{name:true}},images:{where:{isPrimary:true},take:1}};
function map(row){const p=row.product,available=Math.max(0,p.stock-(p.reservedStock||0)),type=p.productType==="SMARTPHONE"?"smartphone":"accessory",route=type==="smartphone"?`/product/${p.slug}`:`/accessory/${p.slug}`;return{wishlistItemId:row.id,wishlistKey:`${type}-${p.id}`,productId:p.id,id:p.id,legacyId:p.legacyId,slug:p.slug,name:p.name,productType:type,brand:p.brand.name,category:p.category.name,price:Number(p.price),originalPrice:p.originalPrice?Number(p.originalPrice):null,imageUrl:p.imageUrl,image:p.imageUrl,stock:available,availableStock:available,inStock:p.isActive&&available>0,lowStock:p.isActive&&available>0&&available<=p.lowStockThreshold,isActive:p.isActive,route,detailRoute:route,addedAt:row.createdAt,rating:p.rating?Number(p.rating):null}}
async function resolve(identifier,extra={}){const value=String(identifier||"").trim(),legacy=/^\d+$/.test(value)?Number(value):null;return prisma.product.findFirst({where:{OR:[{id:value},{slug:value},...(legacy!==null?[{legacyId:legacy}]:[]),...(extra.slug?[{slug:String(extra.slug)}]:[]),...(extra.legacyId!==undefined&&/^\d+$/.test(String(extra.legacyId))?[{legacyId:Number(extra.legacyId)}]:[])]}})}
export async function list(userId,q={}){const page=Math.max(1,Number(q.page)||1),limit=Math.min(50,Math.max(1,Number(q.limit)||20)),sort={newest:{createdAt:"desc"},oldest:{createdAt:"asc"},"price-asc":{product:{price:"asc"}},"price-desc":{product:{price:"desc"}},"name-asc":{product:{name:"asc"}}}[q.sort||"newest"];if(!sort)throw new WishlistError(422,"INVALID_SORT","Invalid wishlist sort.");const productType=q.productType&&q.productType!=="all"?q.productType.toUpperCase():null;if(productType&&!['SMARTPHONE','ACCESSORY'].includes(productType))throw new WishlistError(422,"INVALID_TYPE","Invalid product type.");const where={userId,...(productType?{product:{productType}}:{}),...(q.availability==="unavailable"?{product:{isActive:false}}:q.availability==="in-stock"?{product:{isActive:true,stock:{gt:0}}}:q.availability==="out-of-stock"?{product:{isActive:true,stock:0}}:{})};const[rows,total]=await prisma.$transaction([prisma.wishlistItem.findMany({where,include:{product:{include:productInclude}},orderBy:sort,skip:(page-1)*limit,take:limit}),prisma.wishlistItem.count({where})]);return{items:rows.map(map),pagination:{page,limit,total,totalPages:Math.ceil(total/limit),hasNextPage:page*limit<total,hasPreviousPage:page>1}}}
export async function add(userId,identifier){const p=await resolve(identifier);if(!p)throw new WishlistError(404,"WISHLIST_PRODUCT_NOT_FOUND","This product is no longer available.");if(!p.isActive)throw new WishlistError(409,"WISHLIST_PRODUCT_INACTIVE","This product is currently unavailable.");const existing=await prisma.wishlistItem.findUnique({where:{userId_productId:{userId,productId:p.id}},include:{product:{include:productInclude}}});if(existing)return{item:map(existing),count:await prisma.wishlistItem.count({where:{userId}}),created:false};if(await prisma.wishlistItem.count({where:{userId}})>=LIMIT)throw new WishlistError(409,"WISHLIST_LIMIT_REACHED","Your wishlist has reached its maximum size.");const row=await prisma.wishlistItem.create({data:{userId,productId:p.id},include:{product:{include:productInclude}}});return{item:map(row),count:await prisma.wishlistItem.count({where:{userId}}),created:true}}
export async function remove(userId,identifier){const p=await resolve(identifier);if(p)await prisma.wishlistItem.deleteMany({where:{userId,productId:p.id}});return{count:await prisma.wishlistItem.count({where:{userId}})}}
export async function toggle(userId,identifier){const p=await resolve(identifier);if(!p)throw new WishlistError(404,"WISHLIST_PRODUCT_NOT_FOUND","This product is no longer available.");const existing=await prisma.wishlistItem.findUnique({where:{userId_productId:{userId,productId:p.id}}});if(existing){await prisma.wishlistItem.delete({where:{id:existing.id}});return{wishlisted:false,productId:p.id,count:await prisma.wishlistItem.count({where:{userId}})}}const result=await add(userId,p.id);return{wishlisted:true,productId:p.id,count:result.count,item:result.item}}
export async function merge(userId,items){if(!Array.isArray(items)||items.length>100)throw new WishlistError(422,"INVALID_MERGE","Send up to 100 guest wishlist items.");let added=0,alreadyPresent=0,unavailable=0,invalid=0;for(const input of items){if(!input||(!input.productId&&!input.slug&&input.legacyId===undefined)){invalid++;continue}const p=await resolve(input.productId||input.slug||input.legacyId,input);if(!p||!p.isActive){unavailable++;continue}const exists=await prisma.wishlistItem.findUnique({where:{userId_productId:{userId,productId:p.id}}});if(exists){alreadyPresent++;continue}if(await prisma.wishlistItem.count({where:{userId}})>=LIMIT)break;try{await prisma.wishlistItem.create({data:{userId,productId:p.id}});added++}catch(e){if(e.code==="P2002")alreadyPresent++;else throw e}}return{added,alreadyPresent,unavailable,invalid,total:await prisma.wishlistItem.count({where:{userId}})}}
export async function status(userId,ids){if(!Array.isArray(ids)||ids.length>100)throw new WishlistError(422,"INVALID_STATUS_REQUEST","Send up to 100 product IDs.");const rows=await prisma.wishlistItem.findMany({where:{userId,productId:{in:ids.map(String)}},select:{productId:true}});return{wishlistedProductIds:rows.map(x=>x.productId),count:await prisma.wishlistItem.count({where:{userId}})}}
export async function clear(userId){await prisma.wishlistItem.deleteMany({where:{userId}});return{count:0}}
